project:
  type: book
  output-dir: docs
  
book:
  title: "Portfolio"
  author: "Guk Yu"
  date: "26/10/2023"
  chapters:
    - index.qmd
    - women-15minute-city.qmd
    - e-scooter-active-travel.qmd
    - airbnb-hotel-culture-policy.qmd
    - london-queer-population.qmd
    - london-underground-heat-resilience-index.qmd
    - stop-search-frisk.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo, flatly]
        dark: [cosmo, darkly]
       
  pdf:
    documentclass: scrreprt

editor: visual

